// AUTO-GENERATED by scripts/gen-voiceover.mjs — do not edit by hand.
// Run `node scripts/gen-voiceover.mjs` (or FORCE=1 …) to regenerate.

export type VoiceLine = {
  id: string;
  file: string;
  text: string;
  seconds: number;
  frames: number;
};

export const FPS = 30;

export const VOICEOVER: VoiceLine[] = [
  {
    "id": "hook",
    "file": "vo/line1-hook.mp3",
    "text": "Your clinic runs on conversations. Managing all of them is where most operations fall short.",
    "seconds": 5.825,
    "frames": 175
  },
  {
    "id": "meet",
    "file": "vo/line2-meet.mp3",
    "text": "Meet Mimira — the all-in-one AI platform built to help clinics unlock the opportunity from every conversation, and drive more revenue.",
    "seconds": 8.411,
    "frames": 253
  },
  {
    "id": "answer",
    "file": "vo/line3-answer.mp3",
    "text": "Mimira answers every customer twenty-four seven, warmly — turning conversations into booked sales and appointments, instantly.",
    "seconds": 7.366,
    "frames": 221
  },
  {
    "id": "channels",
    "file": "vo/line4-channels.mp3",
    "text": "Conversations move seamlessly across all your social apps, with natural, human-like response times.",
    "seconds": 5.956,
    "frames": 179
  },
  {
    "id": "inbox",
    "file": "vo/line5-inbox.mp3",
    "text": "And with Mimira's staff inbox, your team can monitor, manage, and jump into any conversation when a human touch is needed.",
    "seconds": 7.262,
    "frames": 218
  },
  {
    "id": "outbound",
    "file": "vo/line6-outbound.mp3",
    "text": "But Mimira doesn't just respond. With intelligent outbound, Mimira reaches customers first — sending promotions they're likely to buy, and automatically following up with aftercare, appointment reminders, and more.",
    "seconds": 11.807,
    "frames": 355
  },
  {
    "id": "outro",
    "file": "vo/line7-outro.mp3",
    "text": "Unlock the value of every conversation, with Mimira — the all-in-one intelligence and automation platform for the AI-driven clinic.",
    "seconds": 8.229,
    "frames": 247
  }
];
