// AUTO-GENERATED by scripts/gen-voiceover.mjs — do not edit by hand.
// Run `node scripts/gen-voiceover.mjs` (or FORCE=1 …) to regenerate.

export type VoiceLine = {
  id: string;
  file: string;
  text: string;
  seconds: number;
  frames: number;
};

export const FPS = 30;

export const VOICEOVER: VoiceLine[] = [
  {
    "id": "hook",
    "file": "vo/line1-hook.mp3",
    "text": "Your clinic runs on conversations. Managing all of them is where most operations fall short.",
    "seconds": 5.277,
    "frames": 159
  },
  {
    "id": "meet",
    "file": "vo/line2-meet.mp3",
    "text": "Meet Mimira AI — the all-in-one AI platform built to help clinics unlock the opportunity from every conversation, and drive more revenue.",
    "seconds": 8.751,
    "frames": 263
  },
  {
    "id": "answer",
    "file": "vo/line3-answer.mp3",
    "text": "Mimira answers every customer twenty-four seven, turning conversations into booked sales and appointments instantly.",
    "seconds": 6.557,
    "frames": 197
  },
  {
    "id": "channels",
    "file": "vo/line4-channels.mp3",
    "text": "Conversations move seamlessly across all social apps, with natural, human-like response times.",
    "seconds": 5.877,
    "frames": 177
  },
  {
    "id": "inbox",
    "file": "vo/line5-inbox.mp3",
    "text": "And with Mimira's staff inbox, your team can monitor, manage, and jump into any conversation when a human touch is needed.",
    "seconds": 7.262,
    "frames": 218
  },
  {
    "id": "outbound",
    "file": "vo/line6-outbound.mp3",
    "text": "But Mimira doesn't just respond. With intelligent outbound capabilities, Mimira can reach customers first, sending promotions they're likely to buy, automatically following up with aftercare, appointment reminders, and more.",
    "seconds": 13.531,
    "frames": 406
  },
  {
    "id": "outro",
    "file": "vo/line7-outro.mp3",
    "text": "Unlock the value of every conversation with Mimira, the all-in-one intelligence and automation platform for the AI-driven clinic.",
    "seconds": 7.575,
    "frames": 228
  }
];
